CREATE DATABASE DELIVERX;

CREATE USER deliverx WITH PASSWORD 'deliverx';

GRANT CONNECT ON DATABASE DELIVERX TO deliverx;

\connect DELIVERX

GRANT USAGE ON SCHEMA public TO deliverx;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO deliverx;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO deliverx;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO deliverx;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE
ON SEQUENCES TO deliverx;

ALTER USER postgres WITH PASSWORD '0123489frjoiwedfgj';
