services:
  redis:
    image: redis:7
    network_mode: "host"

  deliverx-producer:
    image: deliverx:1.0
    build:
      context: .
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

  
  deliverx-consumer-1:
    image: deliverx:1.0
    build:
      context: .
    command: ["uv", "run", "python", "deliverx/scripts/start_kafka_consumer.py"]
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

  deliverx-consumer-2:
    image: deliverx:1.0
    build:
      context: .
    command: ["uv", "run", "python", "deliverx/scripts/start_kafka_consumer.py"]

    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

  deliverx-consumer-3:
    image: deliverx:1.0
    build:
      context: .
    command: ["uv", "run", "python", "deliverx/scripts/start_kafka_consumer.py"]
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

  deliverx-consumer-4:
    image: deliverx:1.0
    build:
      context: .
    command: ["uv", "run", "python", "deliverx/scripts/start_kafka_consumer.py"]
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

  deliverx-celery-beat:
    image: deliverx:1.0
    build:
      context: .
    command: ["uv", "run", "celery", "-A", "deliverx.configuration.celery_app:celery_app", "worker", "--beat", "--loglevel=info"]
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

volumes:
  app-logs:
