services:
  deliverx-producer:
    image: deliverx:1.0
    build:
      context: .
    ports:
      - "8000:8000"
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

  
  deliverx-consumer-1:
    image: deliverx:1.0
    build:
      context: .
    command: ["uv", "run", "python", "deliverx/scripts/start_kafka_consumer.py"]
    ports:
      - "8000:8000"
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

  deliverx-consumer-2:
    image: deliverx:1.0
    build:
      context: .
    command: ["uv", "run", "python", "deliverx/scripts/start_kafka_consumer.py"]

    ports:
      - "8000:8000"
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

  deliverx-consumer-3:
    image: deliverx:1.0
    build:
      context: .
    command: ["uv", "run", "python", "deliverx/scripts/start_kafka_consumer.py"]
    ports:
      - "8000:8000"
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

  deliverx-consumer-4:
    image: deliverx:1.0
    build:
      context: .
    command: ["uv", "run", "python", "deliverx/scripts/start_kafka_consumer.py"]
    ports:
      - "8000:8000"
    network_mode: "host"
    volumes:
      - ./app-logs:/app/app-logs

volumes:
  app-logs: