"""Initial migration

Revision ID: 396176070726
Revises: 
Create Date: 2026-05-20 19:30:50.931145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396176070726'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id_notification', sa.Integer(), nullable=False),
    sa.Column('id_api_request', sa.Text(), nullable=False),
    sa.Column('js_content', sa.JSON(), nullable=False),
    sa.Column('arr_types', sa.ARRAY(sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'IN_APP', name='notification_delivery_medium_enum')), nullable=False),
    sa.Column('tx_trigger_event', sa.Text(), nullable=True),
    sa.Column('ts_created_on', sa.TIMESTAMP(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_notification'),
    sa.UniqueConstraint('id_api_request')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
