"""added status columns with right enums

Revision ID: e50e2393920e
Revises: 396176070726
Create Date: 2026-05-21 12:30:37.580584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e50e2393920e'
down_revision: Union[str, Sequence[str], None] = '396176070726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    outbox_event_status_enum = postgresql.ENUM(
        'pending',
        'processing',
        'sent',
        'failed',
        'retrying',
        'dead_lettered',
        name='outbox_event_status_enum',
    )
    notification_channel_status_enum = postgresql.ENUM(
        'pending',
        'processing',
        'sent',
        'delivered',
        'retrying',
        'failed',
        'skipped',
        'cancelled',
        name='notification_channel_status_enum',
    )
    notification_status_enum = postgresql.ENUM(
        'queued',
        'processing',
        'partially_delivered',
        'delivered',
        'failed',
        'cancelled',
        name='notification_status_enum',
    )

    bind = op.get_bind()
    outbox_event_status_enum.create(bind, checkfirst=True)
    notification_channel_status_enum.create(bind, checkfirst=True)
    notification_status_enum.create(bind, checkfirst=True)
    op.alter_column(
        'notifications',
        'id_user',
        existing_type=sa.Integer(),
        type_=sa.Text(),
        existing_nullable=False,
    )

    op.create_table('outbox_events',
    sa.Column('id_outbox_event', sa.Integer(), nullable=False),
    sa.Column('aggregate_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'sent', 'failed', 'retrying', 'dead_lettered', name='outbox_event_status_enum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_outbox_event')
    )
    op.create_table('notification_channels',
    sa.Column('id_notification_channel', sa.Integer(), nullable=False),
    sa.Column('id_notification', sa.Integer(), nullable=False),
    sa.Column('channel', postgresql.ENUM('EMAIL', 'SMS', 'WHATSAPP', 'IN_APP', name='notification_delivery_medium_enum', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'sent', 'delivered', 'retrying', 'failed', 'skipped', 'cancelled', name='notification_channel_status_enum', create_type=False), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_notification'], ['notifications.id_notification'], ),
    sa.PrimaryKeyConstraint('id_notification_channel')
    )
    op.add_column('notifications', sa.Column('status', postgresql.ENUM('queued', 'processing', 'partially_delivered', 'delivered', 'failed', 'cancelled', name='notification_status_enum', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'status')
    op.drop_table('notification_channels')
    op.drop_table('outbox_events')
    op.alter_column(
        'notifications',
        'id_user',
        existing_type=sa.Text(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using='id_user::integer',
    )
    postgresql.ENUM(name='notification_status_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='notification_channel_status_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='outbox_event_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
